# Generated by Django 5.1.1 on 2025-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_telegramlinktoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='login',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
