# Generated by Django 5.1.1 on 2025-03-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_chat_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
